# Generated by Django 5.1.7 on 2025-03-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
    ]
